export const GET_PATIENTS="GET_PATIENTS";
export const PATIENTS_ERR="PATIENT_ERRR"
export const PATIENT_LOADING="PATIENT_LOADING"
export const ADD_PATIENTS="PATIENTS"
export const FILTER_PATIENT="FILTER_PATIENT"
